pipeline {
    agent none
    stages {
        stage("Build") {
            agent {
                docker {
                    image 'python:3.11.5-alpine3.18'
                }
            }
            steps {
                sh "python --version"
                sh "pip install -r requirements.txt"
                sh "python main.py"
            }
        }
    }
}